name: Test

on:
  [pull_request, workflow_dispatch]

jobs:
  test:
    name: Rust ${{matrix.rust}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [1.60.0, stable, beta, nightly]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{matrix.rust}}
      - run: cargo check
      - run: cargo build
      - run: cargo test

  test-no-std:
    name: Rust ${{matrix.rust}} ${{matrix.features}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check --no-default-features
      - run: cargo build --no-default-features
      - run: cargo test --no-default-features
